In [4]:
import streamlit as st 
import pandas as pd 
import urllib 
import json 
from helpers import *

2025-05-23 16:32:47.575 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [2]:
station_url = "https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status"
latlon_url = "https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information"

In [8]:
df1 = query_station_status(station_url)

In [7]:
df2 = get_station_latlon(latlon_url)

In [9]:
join_latlon(df1, df2)

,station_id,num_bikes_available,num_bikes_available_types,num_bikes_disabled,num_docks_available,num_docks_disabled,last_reported,is_charging_station,status,is_installed,is_renting,is_returning,traffic,mechanical,ebike,lat,lon
0,7000,4,"{'mechanical': 4, 'ebike': 0}",1,42,0,2025-05-23 22:35:10,False,IN_SERVICE,1,1,1,None,4,0,43.639832,-79.395954
1,7001,2,"{'mechanical': 0, 'ebike': 2}",2,19,0,2025-05-23 22:36:29,True,IN_SERVICE,1,1,1,None,0,2,43.664964,-79.383550
2,7002,1,"{'mechanical': 1, 'ebike': 0}",0,18,0,2025-05-23 22:35:09,False,IN_SERVICE,1,1,1,None,1,0,43.667131,-79.399555
3,7003,8,"{'mechanical': 8, 'ebike': 0}",0,6,1,2025-05-23 22:34:12,False,IN_SERVICE,1,1,1,None,8,0,43.667018,-79.402796
4,7005,6,"{'mechanical': 5, 'ebike': 1}",0,17,0,2025-05-23 22:35:18,False,IN_SERVICE,1,1,1,None,5,1,43.648001,-79.383177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,8034,0,"{'mechanical': 0, 'ebike': 0}",0,15,0,2025-05-23 22:36:29,False,IN_SERVICE,1,1,1,None,0,0,43.729522,-79.510143
882,8035,0,"{'mechanical': 0, 'ebike': 0}",0,19,0,2025-05-23 22:36:22,False,IN_SERVICE,1,1,1,None,0,0,43.728618,-79.478001
883,8025,11,"{'mechanical': 11, 'ebike': 0}",0,0,0,2025-05-23 22:35:16,False,IN_SERVICE,1,1,1,None,11,0,43.647624,-79.375525
884,8036,0,"{'mechanical': 0, 'ebike': 0}",0,18,1,2025-05-23 22:36:20,False,IN_SERVICE,1,1,1,None,0,0,43.739013,-79.512863
885,8037,0,"{'mechanical': 0, 'ebike': 0}",0,15,0,2025-05-23 22:34:11,False,IN_SERVICE,1,1,1,None,0,0,43.755176,-79.438122